name: Scaffold a new Spring Boot service
on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
        description: Includes the action's run id
      service_name:
        required: true
        description: The name of the new service
        type: string
      service_group:
        required: true
        description: The group of the new service (e.g. com.example)
        type: string
jobs:
  scaffold-service:
    env:
      ORG_NAME: JerebChase
    runs-on: ubuntu-latest
    steps:
      - uses: port-labs/cookiecutter-gha@v1.1.1
        id: scaff
        with:
          portClientId: ${{ secrets.PORT_CLIENT_ID }}
          portClientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          portRunId: ${{ fromJson(inputs.port_context).runId }}
          repositoryName: ${{ inputs.service_name }}
          portUserInputs: '{"cookiecutter_name": "${{ inputs.service_name }}", "cookiecutter_group": "${{ inputs.service_group }}" }'
          cookiecutterTemplate: https://github.com/JerebChase/cookiecutter-spring-boot
          blueprintIdentifier: "service"
          organizationName: ${{ env.ORG_NAME }}
