name: Scaffold a new Spring Boot service
on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
        description: Includes the action's run id
      aws_account:
        required: true
        description: The AWS account number
        type: string
      role_arn:
        required: true
        description: The role ARN to for the github action to assume
        type: string
      service_name:
        required: true
        description: The name of the new service
        type: string
      repository_name:
        required: true
        description: The name of the Github repository where the service will live
        type: string
      description:
        required: true
        description: The description of the service
        type: string
      private_repo:
        required: true
        description: Whether or not the generated repository should be private
        type: boolean
jobs:
  scaffold-service:
    env:
      ORG_NAME: JerebChase
    runs-on: ubuntu-latest
    steps:
      - uses: JerebChase/cookiecutter-gha-jerebchase@v1.0.11
        id: scaff
        with:
          portClientId: ${{ secrets.PORT_CLIENT_ID }}
          portClientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          portRunId: ${{ fromJson(inputs.port_context).runId }}
          repositoryName: ${{ inputs.repository_name }}
          portUserInputs: '{"cookiecutter_name": "${{ inputs.service_name }}", "cookiecutter_repo": "${{ inputs.repository_name }}", "cookiecutter_description": "${{ inputs.description }}" }'
          cookiecutterTemplate: https://github.com/JerebChase/cookiecutter-spring-boot
          blueprintIdentifier: "service"
          organizationName: ${{ env.ORG_NAME }}
          privateRepo: ${{ inputs.private_repo }}
          awsAccount: ${{ inputs.aws_account }}
          roleArn: ${{ inputs.role_arn }}
